<?php

namespace AppBundle\Repository;

/**
 * CallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallsRepository extends \Doctrine\ORM\EntityRepository
{
}
