<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getCompanies()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select("t")
            ->from("AppBundle:Company","t");
        return $qb->getQuery()->getArrayResult();
    }
}
