<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Company;
use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * Mostrar todas las empresas
     * @return array
     */
    public function getCompanies()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }
}
