<?php

namespace AppBundle\Repository;

/**
 * CallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvocatoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllConvocatories()
    {
        return $this->findAll();
    }
}
