<?php

namespace AppBundle\Repository;

/**
 * Course_cycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Course_cycleRepository extends \Doctrine\ORM\EntityRepository
{
}
