<?php

namespace AppBundle\Repository;

/**
 * CycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CycleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCycles()
    {
        return $this->findAll();
    }

    public function getTotalHours()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('SUM(t.titularHours1) titularHours1, SUM(t.desdobleHours1) desdobleHours1, SUM(t.titularHours2) titularHours2, SUM(t.desdobleHours2) desdobleHours2')
            ->from('AppBundle:Cycle', 't');

        return $qb->getQuery()->getArrayResult();
    }

    public function getHours()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('SUM(c.titularHours1 + c.desdobleHours1 + c.titularHours2 + c.desdobleHours2)')
            ->from('AppBundle:Cycle', 'c');

        $result = $qb->getQuery()->getArrayResult()[0][1];
        return ($result ? $result : 0);
    }

    public function getSumHours()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('SUM(c.titularHours1 + c.titularHours2) totalHours, SUM(c.desdobleHours1 + c.desdobleHours2) totalHoursDesdoble')
            ->from('AppBundle:Cycle', 'c');

        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }

    public function getHours1ByCourseName($courseName)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('c.titularHours1 totalHours, c.desdobleHours1 totalHoursDesdoble')
            ->from('AppBundle:Cycle', 'c')
            ->where('c.initials=:courseName')
            ->setParameter('courseName', $courseName);

        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }

    public function getHours2ByCourseName($courseName)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('c.titularHours2 totalHours, c.desdobleHours2 totalHoursDesdoble')
            ->from('AppBundle:Cycle', 'c')
            ->where('c.initials=:courseName')
            ->setParameter('courseName', $courseName);

        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }
}
