<?php

namespace AppBundle\Repository;

/**
 * Distribution_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Distribution_companyRepository extends \Doctrine\ORM\EntityRepository
{
}
