<?php

namespace AppBundle\Repository;

/**
 * Distribution_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Distribution_companyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDistributionsCompanies()
    {

        $query = $this->getEntityManager()->createQuery("
                                      SELECT cp.name as company_name, CONCAT(st.first_name,' ',st.last_name) as student_name
                                      FROM AppBundle:Distribution_company ds,
                                      AppBundle:Company cp,AppBundle:Student st,
                                      AppBundle:User us 
                                      WHERE ds.user = us.id 
                                      AND ds.student = st.id 
                                      AND ds.company = cp.id");
        return $query->getArrayResult();
    }
}
