<?php

namespace AppBundle\Repository;

/**
 * Distribution_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Distribution_companyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDistributionsCompanies()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('ds, st, us')
            ->from("AppBundle:Distribution_company, AppBundle:Student, AppBundle:User","ds, st, us")
            ->where("ds.user_id = us.id")
            ->andWhere("ds.student_id = st.id");

        return $qb->getQuery()
            ->getArrayResult();

    }
}
