<?php

namespace AppBundle\Repository;

/**
 * Distribution_module_cycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Distribution_module_cycleRepository extends \Doctrine\ORM\EntityRepository
{
}
