<?php

namespace AppBundle\Repository;

/**
 * Distribution_projectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methodp below.
 */

class Distribution_projectRepository extends \Doctrine\ORM\EntityRepository

{
    public function getDistribution(){
        return $this->findAll();
    }

    public function getDistributionConvocatory($convocatory)
    {
        return $this->getEntityManager()->createQuery("
                                      SELECT dp.id ,pj.name as project_name, CONCAT(us.first_name,' ',us.last_name) 
                                      as user_name, CONCAT(st.first_name,' ',st.last_name) as student_name
                                      FROM AppBundle:Distribution_project dp,
                                      AppBundle:Project pj,AppBundle:Student st,
                                      AppBundle:User us 
                                      WHERE dp.user = us.id 
                                      AND dp.student = st.id 
                                      AND dp.project = pj.id
                                      AND st.convocatory = ".intval($convocatory)." ")->getArrayResult();
    }
}
