<?php

namespace AppBundle\Repository;

/**
 * EventCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCalendarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventsBySchoolYear($schoolYear)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('ec')
            ->from('AppBundle:EventCalendar', 'ec')
            ->where('ec.schoolYear = :schoolYear')
            ->setParameter(":schoolYear", $schoolYear);

        return $qb->getQuery()->getArrayResult();
    }

    public function getEventsBySchoolYearAndGroup($currentYear, $group)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('ec')
            ->from('AppBundle:EventCalendar', 'ec')
            ->where('ec.schoolYear = :schoolYear')
            ->andWhere('ec.gr = :group')
            ->setParameter(":schoolYear", $currentYear)
            ->setParameter(":group", $group);

        return $qb->getQuery()->getArrayResult();
    }
}
