<?php

namespace AppBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModules()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t, u.initials')
            ->from('AppBundle:Module', 't')
            ->join('t.group', 'u');

        return $qb->getQuery()->getArrayResult();
    }

    public function getAllModules()
    {
        return $this->findAll();
    }

    public function getActualHoursByGroup($group)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('SUM(t.hours) titularHours, SUM(t.hoursDesdoble) desdobleHours')
            ->from('AppBundle:Module', 't')
            ->join('t.group', 'u')
            ->where('u.initials LIKE :group')
            ->setParameter('group', '%' . $group . '%');

        return $qb->getQuery()->getArrayResult();
    }
}
