<?php

namespace AppBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModules()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('m, CONCAT(cc.course, cy.name) course')
            ->from('AppBundle:Module', 'm')
            ->join('m.course_cycle', 'cc')
            ->join('cc.cycle', 'cy');


        return $qb->getQuery()->getArrayResult();
    }

    public function getAllModules()
    {
        return $this->findAll();
    }

    public function getActualHoursByGroup($group)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('SUM(t.hours) titularHours, SUM(t.hoursDesdoble) desdobleHours')
            ->from('AppBundle:Module', 't')
            ->join('t.course_cycle', 'cc')
            ->join('cc.school_groups', 'g')
            ->where('g.gr = :group')
            ->setParameter('group', $group);

        return $qb->getQuery()->getArrayResult();
    }
}
