<?php

namespace AppBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModules()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t, u.name')
            ->from('AppBundle:Module', 't')
            ->join('t.cycle', 'u');

        return $qb->getQuery()->getArrayResult();
    }
}
