<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Mostrar todos los proyectos
     * @return array
     */
    public function getProjects()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }
}
