<?php

namespace AppBundle\Repository;

/**
 * Request_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Request_companyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRequestCompanies()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select("t")
            ->from("AppBundle:Request_company","t");
        return $qb->getQuery()->getArrayResult();
    }
}
