<?php

namespace AppBundle\Repository;

/**
 * Request_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Request_companyRepository extends \Doctrine\ORM\EntityRepository
{
}
