<?php

namespace AppBundle\Repository;

/**
 * Request_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Request_companyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRequestCompanies($convocatory)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('sy.id')
            ->from('AppBundle:Convocatory', 'c')
            ->join('c.schoolYear', 'sy')
            ->where('c.id = :convocatory_id')
            ->setParameter('convocatory_id',$convocatory);

        $currentYear = $qb->getQuery()->getResult()[0]["id"];
        return $this->findBy(array("schoolYear" => $currentYear));
    }
}
