<?php

namespace AppBundle\Repository;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCourses()
    {
        return $this->findAll();
    }
}
