<?php

namespace AppBundle\Repository;

/**
 * SchoolYear_convocatoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYear_convocatoryRepository extends \Doctrine\ORM\EntityRepository
{
}
