<?php

namespace AppBundle\Repository;

/**
 * School_groupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class School_groupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGroups()
    {
        return $this->findAll();
    }
}
