<?php

namespace AppBundle\Repository;

/**
 * School_groupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class School_groupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGroups()
    {
        return $this->findAll();
    }

    public function getGroupsCourse($course)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('sg')
            ->from('AppBundle:School_group', 'sg')
            ->join('sg.course_cycle', 'cc')
            ->where('cc.course = :course')
            ->setParameter('course', $course);

        return $qb->getQuery()->getResult();
    }

}
