<?php

namespace AppBundle\Repository;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCourses()
    {
        return $this->findBy(array(), array('course' => 'DESC'));
    }

    public function getLastCourse()
    {
        return $this->findOneBy(array(), array('course' => 'DESC'));
    }

    public function getCourseByConvocatory($currentConvocatory)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('sy.id')
            ->from('AppBundle:Convocatory', 'co')
            ->join('co.schoolYear', 'sy')
            ->where("co.id=:currentConvocatory")
            ->setParameter('currentConvocatory', $currentConvocatory);

        return $qb->getQuery()->getArrayResult();
    }
}
