<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllStudents()
    {
        return $this->findAll();
    }

    public function getAllStudentsWithGroup()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t, u.name')
            ->from('AppBundle:Student', 't')
            ->join('t.group', 'u');

        return $qb->getQuery()->getArrayResult();
    }
}
